### ISSUE TITLE
The data retention in medic monitoring is not working it is taking the default value of 2 months even though i changed the value to 6m in Prometheus image 

### ISSUE THREAD

**Issue by vyshakssekhar** [medic/cht-watchdog#92]
```yaml
prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    ports:
      - "${PROMETHEUS_BIND:-127.0.0.1}:${PROMETHEUS_PORT:-9094}:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-6m}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
```      
      
This is just a part of the docker-compose I'm provided from medic using where Prometheus image is used, here in the data retention part I have specified it as 6m but it is not taking that whenever more than 2 months of data comes it deletes the remaining data.I need at least 6 months of data to be there. so what to do
